# Generated by Django 4.1.4 on 2023-02-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='090', help_text='e.g 0903...', max_length=11),
        ),
    ]
