# Generated by Django 4.1.4 on 2023-02-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(help_text='e.g 0903...', max_length=11),
        ),
    ]
