# Generated by Django 4.1.4 on 2023-02-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_payment',
            name='amount',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
    ]
