# Generated by Django 4.1.4 on 2023-02-24 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_payment_options_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='delivery',
            name='L_G_A',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lga'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.delivery_fee'),
        ),
    ]
