# Generated by Django 4.1.4 on 2023-02-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delivery_fee_lga_alter_delivery_l_g_a_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='delivery_fee',
            options={'verbose_name_plural': 'Delivery Fees'},
        ),
        migrations.AlterModelOptions(
            name='lga',
            options={'verbose_name_plural': 'LGAs'},
        ),
        migrations.AddField(
            model_name='delivery_fee',
            name='lga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.lga'),
            preserve_default=False,
        ),
    ]
