# Generated by Django 4.1.4 on 2023-03-07 20:55

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_refund_granted_order_refund_requested'),
        ('core', '0009_continent_country_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('closest_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lga')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('price', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='lga', chained_model_field='lga', on_delete=django.db.models.deletion.CASCADE, to='core.delivery_fee')),
            ],
        ),
    ]
