# Generated by Django 4.1.4 on 2023-03-07 22:02

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_main_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_delivery',
            name='order',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='main_delivery',
            name='price',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='closest_stop', chained_model_field='lga', on_delete=django.db.models.deletion.CASCADE, to='core.delivery_fee'),
        ),
    ]
