# Generated by Django 4.1.4 on 2023-02-17 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_subcategory_supersubcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supersubcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.subcategory'),
            preserve_default=False,
        ),
    ]
