# Generated by Django 4.1.4 on 2023-02-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref',
            field=models.CharField(default='me', max_length=200),
            preserve_default=False,
        ),
    ]
