# Generated by Django 4.1.4 on 2023-03-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_delivery_prices_options_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery_prices',
            old_name='name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='lga',
            old_name='name',
            new_name='city',
        ),
    ]
