# Generated by Django 4.1.4 on 2023-03-10 16:25

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_name_delivery_prices_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='city', chained_model_field='city', on_delete=django.db.models.deletion.CASCADE, to='orders.delivery_prices'),
        ),
    ]
