# Generated by Django 4.1.4 on 2023-03-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=90878262161, max_length=11),
            preserve_default=False,
        ),
    ]
